phc: updated makefiles
Makefiles have been updated to reflect changes made while
upstreaming to starlingx repos.

Signed-off-by: Shinas Rasheed <srasheed@marvell.com>
Change-Id: If4412bb4834e277f8c0f3f11012e66b492f728ec
Reviewed-on: https://sj1git1.cavium.com/c/IP/SW/pcie_ep/pcie_ep_octeon_host/+/104811
Tested-by: sa_ip-sw-jenkins <sa_ip-sw-jenkins@marvell.com>
Reviewed-by: Sathesh B Edara <sedara@marvell.com>

diff --git a/drivers/phc/Makefile b/drivers/phc/Makefile
--- a/drivers/phc/Makefile
+++ b/drivers/phc/Makefile
@@ -1,27 +1,60 @@
-#Copyright (c) 2020 Marvell.
-#SPDX-License-Identifier: GPL-2.0
+# SPDX-License-Identifier: GPL-2.0
+# Copyright (C) 2020 Marvell.
 
-MODULE_MAME = oct_ep_phc
-KERNEL_DIR ?= /lib/modules/$(shell uname -r)/build
+KVER=
+ifeq ($(KVER),)
+  KVER=$(shell uname -r)
+endif
 
-SRCS = ep_phc.c octeon_device.c
+LINUX=/lib/modules/$(KVER)/build
+ifeq ($(shell ls /lib/modules/$(KVER)/source > /dev/null 2>&1 && echo source),)
+  LINUXSRC=$(LINUX)
+else
+  LINUXSRC=/lib/modules/$(KVER)/source
+endif
 
-INCLUDE_DIR = -I$(PWD)/include
+KDIR ?= $(srctree)
+ifneq ($(KDIR),)
+  LINUX=$(KDIR)
+  LINUXSRC=$(LINUX)
+endif
 
+OCT_DRIVER := oct_ep_phc
+OCT_INSTALL_DIR=/lib/modules/$(KVER)/updates/drivers/net/ethernet/marvell/$(OCT_DRIVER)
 
+override EXTRA_CFLAGS += -g -Werror -Wno-error=date-time -Wno-error=unused-variable -Wno-error=unused-function -I$(shell pwd)/include
 
-ccflags-y := $(INCLUDE_DIR)
-KBUILD_EXTRA_SYMBOLS := $(PCIE_HOST)/Module.symvers
-ccflags-y +=  -Wno-error=date-time
-OBJS =  $(SRCS:.c=.o)
+cflags-y += $(EXTRA_CFLAGS)
 
-obj-m += $(MODULE_MAME).o
-$(MODULE_MAME)-y = $(OBJS)
+OCT_MODULE = $(OCT_DRIVER).ko
 
+ifneq ($(KERNELRELEASE),)
+
+obj-m += ${OCT_DRIVER}.o
+${OCT_DRIVER}-y := ep_phc.o octeon_device.o
+
+else
 
 all:
-	make KBUILD_VERBOSE=1 -C $(KERNEL_DIR) M=`pwd` modules
+	make -C $(LINUX) M=$(shell pwd) modules EXTRA_CFLAGS="$(EXTRA_CFLAGS)"
+
+modules_install:
+	$(MAKE) -C $(LINUXSRC) M=$(shell pwd) modules_install
+
+endif
+
+install: all
+	@if [ "$(KDIR)" != "" ]; then \
+	echo "Cannot use install with KDIR option"; exit 2;\
+	fi
+	mkdir -p $(PREFIX)$(OCT_INSTALL_DIR);
+	install -m 444 $(OCT_MODULE) $(PREFIX)$(OCT_INSTALL_DIR);
+	@if [ "$(PREFIX)" = "" ]; then /sbin/depmod -a ;\
+	else echo " *** Run '/sbin/depmod -a' to update the module database.";\
+	fi
+
+.PHONEY: all clean install
 
 clean:
-	make -C $(KERNEL_DIR) M=`pwd` clean
-	@rm -f ep_phc.o.ur-safe $(MODULE_NAME).mod
+	-rm -f *.tar.gz *.ko *.o *.mod.c *.mod.o .*.*.cmd *.cmd *.markers *.order *.symvers
+	-rm -rf .tmp_versions
